MotorServicio/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
		return view('frontend.bienvenida');
	});

Route::get('/home', function () {
		return view('backend.template.app');
	});
Route::post('sesion', [
		'as'   => 'login-post',
		'uses' => 'Auth\AuthController@postLogin',
	]);
Route::get('sesion', [
		'as'   => 'cerrar',
		'uses' => 'Auth\AuthController@Login',
	]);

Route::group(array('middleware' => 'auth'), function () {
		Route::resource('Acceso', 'admin\gbAccesoController');
		Route::resource('Persona', 'admin\gbPersonaController');
		Route::resource('Usuario', 'admin\gbUsuarioController');
		Route::resource('Rol', 'admin\gbRolController');
		Route::resource('Grupo', 'admin\gbGrupoController');
		Route::resource('Opcion', 'admin\gbOpcionController');
		Route::resource('Asignacion', 'admin\gbAsignacionController');
		Route::resource('RolUsuario', 'admin\gbRolUsuarioController');
		Route::get('lenguaje', 'MenuController@lenguaje');

		/***** MOTOR SERVICIOS *****/
		Route::resource('motor-servicios', 'parametricas\motorServiciosController');
		Route::resource('reglas-negocio', 'parametricas\reglasNegocioController');
		Route::resource('Servicios', 'servicios\ServiciosController');
		Route::resource('parametro', 'parametricas\catalogoController');

		Route::get('v1_0/motorServicios/getRestDinamico/{id}', 'parametricas\motorServiciosController@get_restDinamico');
		Route::get('v1_0/motorServicios/lst_motor_servicios', 'parametricas\motorServiciosController@lst_motor_servicios');
		Route::post('v1_0/motorServicios/darBajaMotorServicio', 'parametricas\motorServiciosController@darBajaMotorServicio');
		Route::post('v1_0/motorServicios/actualizarServicio', 'parametricas\motorServiciosController@actualizarServicio');
		Route::post('v1_0/motorServicios/servicioSP', 'parametricas\motorServiciosController@get_restDinamico_servicio');
		Route::post('v1_0/motorServicios/insertarServicio', 'parametricas\motorServiciosController@insertarServicio');

		Route::get('v1_0/motorServicios/ejcutar_REST_API', 'parametricas\motorServiciosController@get_restDinamico_CURL');
		Route::get('v1_0/motorServicios/get_Dato_Servicio/{id}', 'parametricas\motorServiciosController@get_servicioID');
		Route::get('v1_0/motorServicios/llama_Conn', 'parametricas\motorServiciosController@llamarConexionDB');

		Route::get('v1_0/motorServicios/lst_workspace', 'parametricas\motorServiciosController@lst_catalogo');
		Route::post('v1_0/motorServicios/lst_servicios1', 'parametricas\motorServiciosController@lst_servicio1');

		/****** Reglas de Negocio *****/
		Route::post('v1_0/reglanegocio/editarCodigo', 'parametricas\reglasNegocioController@editarCodigo');
		Route::get('v1_0/reglaNegosio/get_Codigo/{id}', 'parametricas\reglasNegocioController@get_restCodigo');

		Route::get('v1_0/reglaNegocio/lst_reglasNegocio', 'parametricas\reglasNegocioController@lst_reglasNegocio');
		Route::post('v1_0/reglaNegocio/lst_reglasNegocio1', 'parametricas\reglasNegocioController@lst_reglasNegocio1');

		Route::post('v1_0/reglaNegocio/nuevo_registro', 'parametricas\reglasNegocioController@insertarRegla');
		Route::post('v1_0/reglaNegocio/darBajaRegla_Negocio', 'parametricas\reglasNegocioController@darBajaRegla_Negocio');
		Route::get('v1_0/reglaNegocio/get_Combo', 'parametricas\reglasNegocioController@lst_reglasNegocioCombo');
		Route::post('v1_0/reglaNegocio/up_DataCodigo', 'parametricas\reglasNegocioController@editarDataCodigo');
		Route::post('v1_0/reglaNegocio/coneccionDB', 'parametricas\reglasNegocioController@conexionMongoDB');
		Route::get('v1_0/reglaNegocio/get_datos_Codigo/{id}', 'parametricas\reglasNegocioController@get_reglanegocioID');

		Route::get('v1_0/reglanegocio/ejecutar_REST', 'parametricas\reglasNegocioController@ejecutarREST');
		Route::get('v1_0/reglaNegocio/ejecutar_Query', 'parametricas\reglasNegocioController@ejecutarQuery');
		Route::get('v1_0/reglanegocio/ejecutar_Conn', 'parametricas\reglasNegocioController@ejecutarConexionDB');
		Route::get('v1_0/reglaNegocio/get_ServiciosRS/{tipo}', 'parametricas\reglasNegocioController@lst_reglasServicioCombo');
		Route::post('v1_0/reglaNegocio/conexion_DB', 'parametricas\reglasNegocioController@get_conexionDB');
		Route::get('v1_0/reglanegocio/ejecutarPaso', 'parametricas\reglasNegocioController@ejecutar_unitario');
		Route::post('v1_0/reglaNegocio/identificador', 'parametricas\reglasNegocioController@identificador');
		//Route::post('v1_0/reglaNegocio/ejecutarWeb','parametricas\reglasNegocioController@ejecutarWeb');

		Route::get('inicio', function () {
				echo 'Bienvenido ';

				// Con la función Auth::user() podemos obtener cualquier dato del usuario
				// que este en la sesión, en este caso usamos su correo y su id
				// Esta función esta disponible en cualquier parte del código
				// siempre y cuando haya un usuario con sesión iniciada
				echo 'Bienvenido '.Auth::user()->usr_usuario.', su Id es: '.Auth::user()->usr_id;
			});
		Route::get('close', [
				'as'   => 'cerrar',
				'uses' => 'Auth\AuthController@close',
			]);

	});

MotorServicio/app/Http/Controllers/admin/gbAsignacionController.php
<?php

namespace gamlp\Http\Controllers\admin;

use Auth;
use gamlp\Http\Controllers\Controller;
use gamlp\Modelo\admin\Acceso;

use gamlp\Modelo\admin\Grupo;

use Illuminate\Http\Request;
use Session;

class gbAsignacionController extends Controller {
	public function index() {
		$rol    = Acceso::getListarRol();
		$opc    = Acceso::getListarOpcion();
		$acceso = Acceso::getListar();
		return view('backend.administracion.admin.gbAsignacion.index', compact('rol', 'opc', 'acceso'));
	}

	public function create() {
		return $grupillo = Grupo::all();
	}

	public function store(Request $request) {

		$valor_boton1 = $request['rolos'];
		if (isset($_POST['opciones'])) {
			$arr_opc = $_POST['opciones'];
			for ($i = 0; $i < count($arr_opc); $i++) {
				Acceso::create([
						'acc_rls_id' => $request['rolos'],
						'acc_opc_id' => $arr_opc[$i],
						'acc_usr_id' => Auth::User()->usr_id,
					]);
			}
			$rol    = Acceso::getListarRol();
			$opc    = Acceso::getListarOpcionParam($valor_boton1);
			$acceso = Acceso::getListarAccesoParam($valor_boton1);
			return view('backend.administracion.admin.gbAsignacion.index', compact('rol', 'opc', 'acceso'));
		} else {
			$arr_acc = $_POST['asignaciones'];
			for ($i = 0; $i < count($arr_acc); $i++) {
				Acceso::where('acc_id', $arr_acc[$i])
					->update(['acc_estado' => 'B']);
			}
			$rol    = Acceso::getListarRol();
			$opc    = Acceso::getListarOpcionParam($valor_boton1);
			$acceso = Acceso::getListarAccesoParam($valor_boton1);
			return view('backend.administracion.admin.gbAsignacion.index', compact('rol', 'opc', 'acceso'));
		}
	}

	public function show($id) {

		$grupo = Grupo::where('grp_id', $id)->update(['grp_estado' => 'B']);
		Session::flash('message', 'Grupo eliminado correctamente');
		$grupillo = Grupo::getListar();
		Session::flash('message', 'El grupo fue eliminado correctamente.');
		return view('admin.gbGrupos.read', compact('grupo', 'grupillo'));
	}
	public function edit($id) {
		$grupo    = Grupo::setBuscar($id);
		$grupillo = Grupo::getListar();
		return view('admin.gbGrupos.update', compact('grupo', 'grupillo'));
	}

	public function update(Request $request, $id) {
		$grupo = Grupo::setBuscar($id);
		$grupo->fill($request->all());
		$grupo->save();
		$grupillo = Grupo::getListar();
		Session::flash('message', 'El grupo se editado Correctamente');
		return view('admin.gbGrupos.read', compact('grupillo'));
	}

	public function destroy($id) {

	}
}

MotorServicio/resources/views/backend/administracion/admin/gbAsignacion/create.blade.php
@extends('backend.template.app')
@section('main-content')
@if(Session::has('message'))
<div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </botton>
    {{Session::get('message')}}
</div>

@endif
<div class="col-md-5 col-md-offset-3">
    <div class="thumbnail">
        <div class="caption">
            <h3 class="text-center"> <b> REGISTRO GRUPOS</b></h3><hr>
            {!! Form::open(array('route' => 'Grupo.store','method'=>'POST','class'=>'')) !!}
            <div class="row">
                <div class="col-md-12">
                    <input type="hidden" name="csrf-token" value="{{ csrf_token() }}" id="token">
                    <div class="form-group">
                        <strong>Nombre de grupo:</strong>
                        {!! Form::text('grp_grupo', null, array('placeholder' => 'Nombre de Grupo','class' => 'form-control')) !!}
                    </div>

                    <div class="form-group">
                      <strong>Imagen:</strong>
                      {!! Form::text('grp_imagen', null, array('placeholder' => 'Nombre de la ruta','class' => 'form-control')) !!}
                  </div>
                  <div class="form-group">
                    <strong>Usuario Id:</strong>
                    {!! Form::text('grp_usr_id', null, array('placeholder' => 'Id usuario','class' => 'form-control')) !!}
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12 text-center"><hr>

                   <p align="right">

                    <a href="{{ route('Grupo.index') }}" class="btn btn-default">&nbsp; Cerrar</a>
                    <button type="submit" class="btn btn-warning" style="background:#61BC8C">Guardar</button></p>
                </div>
            </div>
        </div>
    </div>
    @endsection

MotorServicio/resources/views/backend/administracion/admin/gbAsignacion/index.blade.php
@extends('backend.template.app')

@section('htmlheader_title')
@endsection
@section('main-content')

{!! Form::open(array('route' => 'Asignacion.store','method'=>'POST','class'=>'')) !!}
<h2>
    Accesos
</h2>
<!-- dropdownlist para el rol -->
<div class="btn-group" role="group">
    <div class="form-group">
        <label>
            Roles
        </label>
        <select class="form-control" name="rolos">
            @foreach($rol as $vaciado_rol)
            <option value="{{$vaciado_rol->rls_id}}">
                {{$vaciado_rol->rls_rol}}
            </option>
            @endforeach
        </select>
    </div>
</div>
<!-- este div es para la primera tabla-->
<div>
    <div id="no-more-tables">
        <table border="1" bordercolor="#999" class="col-md-4 table-striped table-condensed cf" id="lts-asignacion">
            <thead class="cf">
                <tr>
                    <th colspan="4">
                        OPCIONES
                    </th>
                </tr>
                <tr>
                    <th>
                        <i class="fa fa-check-square-o fa-2x">
                        </i>
                    </th>
                    <th>
                        Grupo
                    </th>
                    <th>
                        Opcion
                    </th>
                    <th>
                        Contenido
                    </th>
                </tr>
            </thead>
            @foreach($opc as $o)
            <tr>
                <td data-title="Seleccionar">
                    <input id="{{ $o->opc_id }}" name="opciones[]" tabindex="1" type="checkbox" value="{{ $o->opc_id }}">
                    </input>
                </td>
                <td data-title="Grupo">
                    {{ $o->grp_grupo }}
                </td>
                <td data-title="Opcion">
                    {{ $o->opc_opcion }}
                </td>
                <td data-title="Contenido">
                    {{ $o->opc_contenido}}
                </td>
            </tr>
            @endforeach
        </table>
    </div>
    <!--botones-->
    <div class="col-md-2">
        <button class="btn btn-warning" name="agregar" style="background:#61BC8C" type="submit">
            Agregar
        </button>
        <button class="btn btn-warning" name="retirar" style="background:#61BC8C" type="submit">
            Retirar
        </button>
    </div>
    <!--botones-->
    <!-- este div es para la segunda tabla-->
    <div id="no-more-tables">
        <table border="1" bordercolor="#999" class="col-md-4 table-striped table-condensed cf" id="lts-asignacion2">
            <thead class="cf">
                <tr>
                    <th colspan="6">
                        ACCESOS
                    </th>
                </tr>
                <tr>
                    <th>
                        <i class="fa fa-check-square-o fa-2x">
                        </i>
                    </th>
                    <th>
                        Rol
                    </th>
                    <th>
                        Opcion
                    </th>
                    <th>
                        Contenido
                    </th>
                    <th>
                        Registrado
                    </th>
                    <th>
                        Modificado
                    </th>
                </tr>
            </thead>
            @foreach($acceso as $a)
            <tr>
                <td data-title="Seleccionar">
                    <input id="{{ $a->acc_id }}" name="asignaciones[]" tabindex="1" type="checkbox" value=" {{ $a->acc_id }}">
                    </input>
                </td>
                <td data-title="Rol">
                    {{ $a->rls_rol }}
                </td>
                <td data-title="Opcion">
                    {{ $a->opc_opcion }}
                </td>
                <td data-title="Contenido">
                    {{ $a->opc_contenido}}
                </td>
                <td data-title="Contenido">
                    {{ $a->acc_registrado}}
                </td>
                <td data-title="Contenido">
                    {{ $a->acc_modificado}}
                </td>
            </tr>
            @endforeach
        </table>
    </div>
</div>
@endsection
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>
    $(document).ready(function(){
    	$("select").change(function(){
    	var rol = $(this).val();
    	document.getElementById("txtTabla").value = rol;
    	document.getElementById("rls_id").sumit();
    	});
    });
</script>

MotorServicio/resources/views/backend/administracion/admin/gbAsignacion/update.blade.php
@extends('backend.template.app')

@section('main-content')
@if(Session::has('message'))
    <div class="alert alert-success alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    {{Session::get('message')}}
    </div>
  @endif
<div class="col-md-5 col-md-offset-3">
  <div class="thumbnail">
    <div class="caption">
      <h3 class="text-center"><b>Editar Grupo</b></h3><hr>
          {!! Form::model($grupo,['route' => ['Grupo.update',$grupo->grp_id],'method'=>'PUT'])!!}
          <div class="row">
            <div class="col-md-12">
              <div class="form-group">

                  {!!Form::label('nombre', 'Nombre de grupo:')!!}
                  {!! Form::text('grp_grupo', null, ['placeholder' => 'Ingrese el nombre de grupo','class'=>'form-control']) !!}

                   {!!Form::label('imagen', 'Ruta Imagen:')!!}
                   {!! Form::text('grp_imagen', null, ['placeholder' => 'Ruta del icono de imagen','class'=>'form-control']) !!}

                  {!!Form::label('fecha1', 'fecha registro:')!!}
                  {!! Form::text('grp_registrado', null, ['placeholder' => 'Ingrese el nombre de Opcion','class'=>'form-control']) !!}

                  {!!Form::label('fecha2', 'Fecha edicion:')!!}
                  {!! Form::text('grp_modificado', null, ['placeholder' => 'Ingrese el nombre de Opcion','class'=>'form-control']) !!}

                   {!!Form::label('usuarioId', 'Codigo de usuario:')!!}
                   {!! Form::text('grp_usr_id', null, ['placeholder' => 'Ingrese el nombre de Opcion','class'=>'form-control']) !!}

                   {!!Form::label('estado', 'Estado:')!!}
                  {!! Form::text('grp_estado', null, ['placeholder' => 'Ingrese el nombre de Opcion','class'=>'form-control']) !!}

                   <div class="col-xs-12 col-sm-12 col-md-12 text-center"><hr>

                   <p align="right"> <a href="{{ route('Grupo.index') }}" class="btn btn-primary" style="background:#A5A5B2">&nbsp;Cerrar</a>
                    <button type="submit" class="btn btn-primary" style="background:#61BC8C">Modificar</button></p>
            </div>
          </div>
          {!! Form::close() !!}
        </div>
      </div>
    </div>
</div>


@endsection